lanuage: python

python:
  - '3.7'

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: true
    - os: osx
      # osx_image: xcode10.3  # default per 09/2019
      sudo: true
      # env:
      #  - MATRIX_EVAL="brew install cmake gcc@9 && CC=gcc-9 && CXX=g++-9"

#addons:
#  homebrew:
#    packages:
#    - cmake
#    - gcc@9

env:
  global:
  - CACHE_DIR="$HOME/virtualenv"
  - MINICONDA_DIR="$HOME/miniconda"
  - PYTHONIOENCODING=UTF8

before_install:
  - travis/install-conda.sh
  - export PATH="$MINICONDA_DIR/bin:$PATH"
  - hash -r
  - conda install -y numpy   # install optimized numpy first
  - pip install pybind11     # so that nmslib can build
  - pip uninstall --yes ngt ngtpy  # as suggested by NGT devs
  # - eval "${MATRIX_EVAL}" || true
  # - brew link gcc || true
  # - brew link cmake || true
  - travis/install-build.sh  # build and install NGT (others might be added)
  - travis/install-pip.sh    # install all the other requirements

install:
  - python setup.py build
  - python setup.py install

before_script:
  - flake8 --exit-zero .

script:
  - pytest --cov=skhubness

after_success:
  - codecov

before_cache:
  - brew cleanup || true

cache:
  - pip
  - ccache
  - packages
  - directories:
      - "$HOME/.cache/pip"
      - "$HOME/virtualenv"
      - "$HOME/miniconda"
      - "$HOME/Library/Caches/Homebrew"

branches:
  only:
  - master
  - develop
