
jobs:
  include:
    - os: linux
      dist: bionic  # Ubuntu 18.04
      language: python
      python:
        - '3.7'
        - '3.8'
    # See https://blog.travis-ci.com/2019-08-07-extensive-python-testing-on-travis-ci
    # for macos config peculiarities.
    - os: osx
      language: shell
      osx_image:
        - xcode10.3  # Python 3.7
        - xcode11.3  # Python 3.7.5

env:
  global:
  - CACHE_DIR="$HOME/virtualenv"
  - MINICONDA_DIR="$HOME/miniconda"
  - PYTHONIOENCODING=UTF8

before_install:
  - travis/install-conda.sh
  - export PATH="$MINICONDA_DIR/bin:$PATH"
  - hash -r
  - conda install -y numpy                # install optimized numpy first
  - pip install pybind11                  # so that nmslib can build
  - travis/install-pip.sh                 # install all the other requirements
  - travis/install-build-puffinn.sh       # install from cache or build first

install:
  - python3 setup.py build
  - python3 setup.py install

before_script:
  - flake8 --exit-zero .

script:
  - pytest skhubness --cov=skhubness

after_success:
  # Only on linux, all libraries are supported, thus tested
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then codecov; fi

cache:
  - pip
  - ccache
  - packages
  - directories:
      - "$HOME/.cache/pip"
      - "$HOME/virtualenv"
      - "$HOME/miniconda"

branches:
  only:
  - master
  - develop
